name: lists
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dio:

  core:
    path: ../../infrastructure/core
  dependencies:
    path: ../../infrastructure/dependencies
  preferences:
    path: ../../infrastructure/preferences

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl_utils: ^2.8.6
  build_runner: ^2.4.6
flutter:


  uses-material-design: true

  assets:
     - assets/images/Avatar.png
