name: auth

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  core:
    path: ../../../infrastructure/core
  dependencies:
    path: ../../../infrastructure/dependencies
  preferences:
    path: ../../../infrastructure/preferences
  l10n:
    path: ../../../infrastructure/l10n

flutter:
  assets:
     - assets/images/F1logo.png

